# .github/workflows/lighthouse.yml
name: Lighthouse CI

on: [pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Lighthouse
        run: npm install -g @lhci/cli
      - name: Run Lighthouse
        run: lhci autorun
